FROM ubuntu:22.04

RUN apt update
RUN apt install -y libstdc++6 build-essential git cmake g++
RUN apt install -y meson

ARG BUILDDIR=/src/@PROJECT_BINARY_NAME@-build-docker-singlerun

RUN --mount=from=project,target=/src/@PROJECT_BINARY_NAME@ \ 
 cd /src/@PROJECT_BINARY_NAME@ && \
 meson setup $BUILDDIR && \
 meson compile -C ${BUILDDIR} && \
 meson install -C ${BUILDDIR}

CMD ["@PROJECT_BINARY_NAME@"]
