FROM jenkins/jenkins:lts

USER root 

RUN apt update
RUN apt install -y libstdc++6 build-essential git cmake g++
RUN apt install -y clang-format
RUN apt install -y cppcheck
RUN apt install -y valgrind
RUN apt install -y flatpak
RUN apt install -y clang-tidy
RUN apt install -y libgtest-dev
RUN apt install -y libgmock-dev
RUN apt install -y gnuplot

ARG srcD=/src
ARG prefix=/usr

WORKDIR $srcD

ARG prjName=matplotplusplus
ARG matPlotScr=$srcD/$prjName
ARG matPlotBuild=$srcD/$prjName-build-docker-singlerun

RUN git clone https://github.com/alandefreitas/matplotplusplus.git $prjName
RUN cmake -B $matPlotBuild -S $matPlotScr \
    -DMATPLOTPP_BUILD_EXAMPLES=OFF \
    -DMATPLOTPP_BUILD_SHARED_LIBS=ON \
    -DMATPLOTPP_BUILD_TESTS=OFF \
    -DCMAKE_BUILD_TYPE=Release \
    -DCMAKE_INTERPROCEDURAL_OPTIMIZATION=ON \
    -DCMAKE_INSTALL_PREFIX=$prefix
RUN cmake --build $matPlotBuild -j$(nproc)
RUN cmake --install $matPlotBuild --prefix $prefix


CMD ["jenkins.sh"]
