FROM ubuntu:22.04

RUN apt update
RUN apt install -y libstdc++6 build-essential git cmake g++

ARG srcD=/src
ARG prefixD=/usr

WORKDIR $srcD

ARG PLPLOTB=$srcD/plplot-build-docker-singlerun

RUN git clone https://git.code.sf.net/p/plplot/plplot plplot
RUN cmake -B $PLPLOTB -S plplot -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=$prefixD -DENABLE_fortran=OFF
RUN cmake --build $PLPLOTB -j$(nproc)
RUN cmake --install $PLPLOTB --prefix $prefixD


ARG BUILDDIR=$srcD/${PROJECT_BINARY_NAME}-build-docker-singlerun

RUN --mount=from=project,target=/src/${PROJECT_BINARY_NAME} \ 
 cd /src/${PROJECT_BINARY_NAME} && \
 mkdir -vp $BUILDDIR && \
 cmake -S . -B $BUILDDIR -DCMAKE_BUILD_TYPE=Release &&  \
 cmake --build $BUILDDIR -j$(nproc) --target ${PROJECT_BINARY_NAME} && \
 cmake --install $BUILDDIR --prefix $prefixD


CMD ["${PROJECT_BINARY_NAME}"]
