cmake_minimum_required(VERSION 3.13)

# Enabler module for the Microsoft WinUI 3 + C++/WinRT GUI stack.
#
# WinUI 3 is a Windows-only UI framework shipped through the Windows App SDK and
# the C++/WinRT projection (both distributed as NuGet packages) and built with
# the MSVC toolchain. This module makes them available on Windows and exposes the
# winui3::sdk interface target the native UI links against.
#
# On a non-Windows host this module is a deliberate no-op: the portable WinUI3
# orchestration (winui3::WinUI3Initer + the WindowConfig helper) and the
# cross-platform run_winui_application() stub are still built, so the project
# configures, builds and runs its unit/component tests everywhere (handy for the
# CI of the platform-independent logic). The real WinUI 3 window only builds on
# Windows. See src/winui3 and the WinUI 3 documentation section.

option(
  ENABLE_WINUI3
  "Enables the WinUI 3 + C++/WinRT GUI (Windows only; the portable parts + a stub build elsewhere)"
  ON
)

if(NOT ENABLE_WINUI3)
  return()
endif()

if(NOT WIN32)
  message(STATUS "WinUI 3 is a Windows-only framework")
  message(STATUS "Skipping the native Windows App SDK setup; the portable WinUI3 orchestration and the non-Windows run_winui_application() stub will be built instead")
  return()
endif()

if(NOT MSVC)
  message(WARNING "WinUI 3 + C++/WinRT is only supported with the MSVC toolchain")
endif()

# C++/WinRT needs C++17 at minimum; the Windows App SDK projection is happier on
# C++20, so raise the standard when the project asked for something older.
if(CMAKE_CXX_STANDARD LESS 17)
  set(CMAKE_CXX_STANDARD 20 PARENT_SCOPE)
  set(CMAKE_CXX_STANDARD_REQUIRED ON PARENT_SCOPE)
endif()

set(
  TEMPLATE_APP_WINAPPSDK_VERSION "1.6.250228001"
  CACHE STRING "The Microsoft.WindowsAppSDK NuGet package version to restore"
)
set(
  TEMPLATE_APP_CPPWINRT_VERSION "2.0.240111.5"
  CACHE STRING "The Microsoft.Windows.CppWinRT NuGet package version to restore"
)

# Restore the Windows App SDK + C++/WinRT NuGet packages next to the build tree.
find_program(NUGET_EXEC nuget)

set(WINUI3_PACKAGES_DIR "${CMAKE_BINARY_DIR}/winui3-packages")
set(WINUI3_PACKAGES_CONFIG "${CMAKE_BINARY_DIR}/winui3-packages.config")

configure_file(
  "${CMAKE_SOURCE_DIR}/misc/winui3/packages.config.in"
  "${WINUI3_PACKAGES_CONFIG}"
  @ONLY
)

if(NUGET_EXEC)
  execute_process(
    COMMAND "${NUGET_EXEC}" restore "${WINUI3_PACKAGES_CONFIG}"
            -PackagesDirectory "${WINUI3_PACKAGES_DIR}"
    RESULT_VARIABLE WINUI3_NUGET_RESULT
  )
  if(NOT WINUI3_NUGET_RESULT EQUAL 0)
    message(WARNING "NuGet restore of the Windows App SDK / C++/WinRT packages failed (code ${WINUI3_NUGET_RESULT})")
  endif()
else()
  message(WARNING
    "nuget(.exe) was not found - cannot restore the Windows App SDK / C++/WinRT "
    "packages automatically. Install the NuGet CLI (or restore from Visual "
    "Studio) so the winui3::sdk target resolves its headers and libraries.")
endif()

set(WINAPPSDK_ROOT "${WINUI3_PACKAGES_DIR}/Microsoft.WindowsAppSDK.${TEMPLATE_APP_WINAPPSDK_VERSION}")

# The C++/WinRT projection headers (winrt/*.h) are generated by cppwinrt.exe from
# the Windows SDK + Windows App SDK metadata. A Windows host with the Windows SDK
# performs that generation into WINUI3_CPPWINRT_GEN (see the documentation); the
# directory is added to the include path here so the generated headers resolve.
set(
  WINUI3_CPPWINRT_GEN "${CMAKE_BINARY_DIR}/winui3-cppwinrt"
  CACHE PATH "Output directory of the generated C++/WinRT projection headers"
)

add_library(winui3-sdk INTERFACE)
add_library(winui3::sdk ALIAS winui3-sdk)

target_include_directories(
  winui3-sdk INTERFACE
  "${WINUI3_CPPWINRT_GEN}"
  "${WINAPPSDK_ROOT}/include"
)

# WindowsApp.lib provides the base WinRT activation; the Windows App SDK runtime
# bootstrapper lib lets an unpackaged executable load the WinUI 3 runtime.
target_link_libraries(
  winui3-sdk INTERFACE
  WindowsApp.lib
  "${WINAPPSDK_ROOT}/lib/win10-x64/Microsoft.WindowsAppRuntime.Bootstrap.lib"
)

message(STATUS "WinUI 3 SDK target 'winui3::sdk' configured (Windows App SDK ${TEMPLATE_APP_WINAPPSDK_VERSION}, C++/WinRT ${TEMPLATE_APP_CPPWINRT_VERSION})")
