cmake_minimum_required(VERSION 3.13)

include(InstallRequiredSystemLibraries)

set(CPACK_GENERATOR "DEB")
set(CPACK_PACKAGE_NAME ${PROJECT_NAME})
set(CPACK_PACKAGE_VERSION ${PROJECT_VERSION})
set(CPACK_PACKAGE_CONTACT "yuriysydor1991@gmail.com")
set(CPACK_DEB_MAINTAINER "Yuriy Sydor yuriysydor1991@gmail.com")
set(CPACK_DEBIAN_PACKAGE_MAINTAINER "Yuriy Sydor yuriysydor1991@gmail.com")
set(CPACK_DEB_COMPONENT_INSTALL ON)
set(CPACK_PACKAGE_DESCRIPTION ${CMAKE_PROJECT_DESCRIPTION})
set(CPACK_DEB_PACKAGE_ARCHITECTURE "amd64")  # Or arm64

include(CPack)
