FROM ${DOCKERFILE_SINGLE_RUN_BASE_IMAGE_STRING}

RUN apt update
RUN apt install -y libstdc++6 build-essential git cmake g++
RUN apt install -y gnuplot

ARG srcD=/src
ARG prefix=/usr

WORKDIR $srcD

ARG prjName=matplotplusplus
ARG matPlotScr=$srcD/$prjName
ARG matPlotBuild=$srcD/$prjName-build-docker-singlerun

# Matplot++ is cloned, built and erased inside a single layer, so neither the
# sources nor the build tree reach the image.
RUN git clone https://github.com/alandefreitas/matplotplusplus.git $prjName && \
  cmake -B $matPlotBuild -S $matPlotScr \
    -DMATPLOTPP_BUILD_EXAMPLES=OFF \
    -DMATPLOTPP_BUILD_SHARED_LIBS=ON \
    -DMATPLOTPP_BUILD_TESTS=OFF \
    -DCMAKE_BUILD_TYPE=Release \
    -DCMAKE_INTERPROCEDURAL_OPTIMIZATION=ON \
    -DCMAKE_INSTALL_PREFIX=$prefix && \
  cmake --build $matPlotBuild -j$(nproc) && \
  cmake --install $matPlotBuild --prefix $prefix && \
  rm -fr $matPlotScr $matPlotBuild


ARG BUILDDIR=/src/${PROJECT_BINARY_NAME}-build-docker-singlerun

# The sources come in through a bind mount and the build tree is erased right
# after the install, so neither of them reaches the image.
RUN --mount=from=project,target=/src/${PROJECT_BINARY_NAME} \ 
 cd /src/${PROJECT_BINARY_NAME} && \
 mkdir -vp $BUILDDIR && \
 cmake -S . -B $BUILDDIR -DCMAKE_BUILD_TYPE=Release &&  \
 cmake --build $BUILDDIR -j$(nproc) --target ${PROJECT_BINARY_NAME} && \
 cmake --install $BUILDDIR --prefix $prefix && \
 rm -fr $BUILDDIR

USER ${DOCKERFILE_SINGLE_RUN_USER_NAME}

CMD ["${PROJECT_BINARY_NAME}"]
