FROM jenkins/jenkins:lts

USER root 

RUN apt update
RUN apt install -y libstdc++6 build-essential git cmake g++
RUN apt install -y clang-format
RUN apt install -y cppcheck
RUN apt install -y valgrind
RUN apt install -y flatpak
RUN apt install -y clang-tidy
RUN apt install -y libgtest-dev
RUN apt install -y libgmock-dev

ARG srcD=/src
ARG prefixD=/usr

WORKDIR $srcD

ARG PLPLOTB=$srcD/plplot-build-docker-singlerun

RUN git clone https://git.code.sf.net/p/plplot/plplot plplot
RUN cmake -B $PLPLOTB -S plplot -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=$prefixD -DENABLE_fortran=OFF
RUN cmake --build $PLPLOTB -j$(nproc)
RUN cmake --install $PLPLOTB --prefix $prefixD

CMD ["jenkins.sh"]

